### ISSUE TITLE
Feature request: Swap adaptor to aerender

### ISSUE THREAD

**Issue by dzavada** [aws-deadline/deadline-cloud-for-after-effects#75]
### Use Case

Currently, the adapter uses JavaScript to generate a socket when After Effects runs, allowing data to be sent to After Effects for rendering. However, there are several issues with this setup. One major problem is that the documentation doesn’t explain how to properly enable the JavaScript when using the Deadline Worker user. Additionally, if you’re running After Effects in render node mode only, you don’t have access to the UI to check the necessary checkbox, which complicates the process further.

### Proposed Solution

Deadline 10 and most other render controllers typically rely on the command-line version of After Effects, and I recommend adopting this approach as it simplifies the process and eliminates a major potential error. The current installer can encounter socket issues, and on top of that, you need to manually enable settings or edit a text file assuming you know how. Using the standard command-line output streamlines the setup and avoids these complications.

aerender -project <project_path> -comp <comp_name> [options]
-project <project_path>
-comp <comp_name>
-layer <layer_name>
-OMtemplate <template_name>
-RStemplate <render_settings_template>
-output <output_path>
-log <log_file_path>
-rqindex <index_number>
-s <start_frame>
-e <end_frame>
-i <increment>
-mp
-close <DO_NOT_SAVE_CHANGES | SAVE_CHANGES>
-v <ERRORS | WARNINGS | INFO>
-continueOnMissingFootage

**Comment by eherozhao** [comment]
Thanks for your reply. We are having a working PR https://github.com/aws-deadline/deadline-cloud-for-after-effects/pull/63 to support a submitter with aereder cmd only with no adaptor. I think this is what you are asking here. Feel free to try it out.

**Comment by eherozhao** [comment]
We merged the PR and now you can visit `feature_dockable_submitter` to use the submitter and we are working on make it as mainline shortly. Please let us know if you have any feedback on the new submitter.
